version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWD}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080